// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/trending-page/HoloGrid.tsx": () => import("../components/mockups/trending-page/HoloGrid.tsx"),
  "./components/mockups/trending-page/NeonSurge.tsx": () => import("../components/mockups/trending-page/NeonSurge.tsx")
};
