import { Game } from './types';

const ONLINE_GAMES_API_URL = '/api/onlinegames-catalog';
const ONLINE_GAMES_SOURCE_URL = 'https://www.onlinegames.io/media/plugins/genGames/embed.json';
const GAMEPIX_TARGET_CATALOG_SIZE = 600;
const GAMEPIX_PAGE_SIZE = 200;
const GAMEPIX_MAX_PAGES = 5;
const GAMEPIX_API_URL = `/api/gamepix-catalog?limit=${GAMEPIX_TARGET_CATALOG_SIZE}`;
const GAMEPIX_SOURCE_URL = 'https://feeds.gamepix.com/v2/json/';

export const CATALOG_SOURCE = 'onlinegames.io + gamepix' as const;

export const CATEGORY_LIST = [

  'All',
  'Favorites',

  'Recommended',
  'History',
  'Trending',
  'Mods',
  'Mobile Games',
  'Best On Mobile',
  'Action',
  'Adventure',
  'Arcade',
  'Card',
  'Casual',
  'Educational',
  'Fighting',
  'Girls',
  'Horror',
  'Multiplayer',
  '1 Player',
  '2 Player',
  '3 Player',
  '4 Player',
  'Platformer',
  'Puzzle',
  'Racing',
  'Simulator',
  'Sports',
  'Strategy'
];

export const TAGS_LIST: string[] = [
  '1 Player',
  '2 Player',
  '2d',
  '3d',
  'Action',
  'Adventure',
  'Arcade',
  'Arena',
  'Ball',
  'Battle',
  'Battle Royale',
  'Board',
  'Brain',
  'Car',
  'Card',
  'Clicker',
  'Crafting',
  'Driving',
  'Free',
  'Fun',
  'Html5',
  'Io Games',
  'Kids',
  'Mobile',
  'Multiplayer',
  'Parkour',
  'Physics',
  'Puzzle',
  'Racing',
  'Shooting',
  'Simulator',
  'Skill',
  'Sports',
  'Strategy',
  'Unity'
];

interface RawOnlineGame {
  title: string;
  embed: string;
  image: string;
  tags: string;
  description: string;
}

interface RawGamePixGame {
  id: string;
  title: string;
  namespace: string;
  description?: string;
  category?: string;
  orientation?: 'all' | 'landscape' | 'portrait';
  quality_score?: number;
  date_published?: string;
  date_modified?: string;
  banner_image?: string;
  image?: string;
  url: string;
}

const REMOVED_ORIGINAL_GAME_IDS = new Set([

  'snake',
  'snake-classic',
  'tetris',
  'block-stacker',
  '2048',
  '2048-original',
  'breakout',
  'minesweeper',
  'minesweeper-classic',
  'flappy',
  'flappy-bird-classic',
  'dino',
  'dino-runner',
  'memory',
  'memory-match',
  'space-shooter',
  'space-defender',
  'pac-dots',
]);

function slugify(title: string): string {
  const base = title
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return base.slice(0, 72) || 'game';
}

function titleCaseTag(tag: string): string {
  return tag
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

function parseTags(raw: string): string[] {
  return raw
    .split(',')
    .map((tag) => tag.trim().toLowerCase())
    .filter(Boolean)
    .map(titleCaseTag);
}

const AD_HEAVY_GAME_IDS = new Set([
  'stickman-parkour',
  'stickman-gta-city',
  'checkout-frenzy',
  'dublix',
  'escape-car',
  'cube-worlds',
  'burnout-city',
  'basket-hoop',
  'fps-strike',
  'warstrike',
  'fast-food-rush',
  'super-car-driving',
  'egg-car-racing',
  'love-tester-story',
  'cubecraft-survival',
  'chess-freezenova',
  'mini-cars-racing',
]);

function inferCategory(tagList: string[]): string {
  const tags = tagList.join(' ').toLowerCase();
  if (/\b(2 player|3 player|4 player|two player|three player|four player|multiplayer|io games)\b/.test(tags)) return 'Multiplayer';
  if (/\b(first person shooter|shooting|fps|gun|battle royale)\b/.test(tags)) return 'Action';
  if (/\b(racing|drift|driving|traffic|car)\b/.test(tags)) return 'Racing';
  if (/\b(puzzle|logic|mahjong|sudoku|match 3)\b/.test(tags)) return 'Puzzle';
  if (/\b(sports|soccer|football|golf|basketball|baseball)\b/.test(tags)) return 'Sports';
  if (/\b(simulator|tycoon|management|organizing)\b/.test(tags)) return 'Simulator';
  if (/\b(strategy|tower defense)\b/.test(tags)) return 'Strategy';
  if (/\b(adventure|parkour|running|platformer|horror|scary|zombie|survival)\b/.test(tags)) return 'Adventure';
  if (/\b(fighting|martial arts|ninja|combat|duel|brawl|fighter)\b/.test(tags)) return 'Fighting';
  if (/\b(arcade|retro|classic)\b/.test(tags)) return 'Arcade';
  if (/\b(action|battle|war)\b/.test(tags)) return 'Action';
  if (/\b(casual|fun|kids)\b/.test(tags)) return 'Casual';
  return 'Arcade';
}

function hasPlayerTag(game: Game, playerCount: 1 | 2 | 3 | 4): boolean {
  const target = `${playerCount} Player`.toLowerCase();
  return (game.tags ?? []).some((tag) => tag.toLowerCase() === target);
}

export function gameMatchesCategory(game: Game, category: string): boolean {
  if (category === 'Mobile Games' || category === 'Best On Mobile') {
    return game.mobileOptimization === 'touch-friendly' ||
      game.mobileOptimization === 'responsive' ||
      (game.tags ?? []).some((tag) => /\b(mobile|touch)\b/i.test(tag));
  }

  if (category === 'Multiplayer') {
    return game.category === 'Multiplayer' ||
      (game.tags ?? []).some((tag) => /\b(multiplayer|io games|2 player|3 player|4 player)\b/i.test(tag));
  }

  if (category === '1 Player') return hasPlayerTag(game, 1);
  if (category === '2 Player') return hasPlayerTag(game, 2);
  if (category === '3 Player') return hasPlayerTag(game, 3);
  if (category === '4 Player') return hasPlayerTag(game, 4);

  return game.category === category || (game.tags ?? []).some((tag) => tag.toLowerCase() === category.toLowerCase());
}

function hashSeed(value: string): number {
  let hash = 0;
  for (let i = 0; i < value.length; i += 1) {
    hash = value.charCodeAt(i) + ((hash << 5) - hash);
  }
  return Math.abs(hash);
}

function seededRating(id: string): number {
  return Math.round((4.0 + (hashSeed(id) % 10) / 10) * 10) / 10;
}

function seededPlays(id: string): number {
  return 15000 + (hashSeed(`${id}-plays`) % 2500000);
}

function bestThumbnailVariant(image: string): string {
  return image
    .trim()
    .replace(/-xs\.webp$/i, '-lg.webp')
    .replace(/-md\.webp$/i, '-lg.webp')
    .replace(/-xs\.(jpg|jpeg|png)$/i, '-lg.$1')
    .replace(/-md\.(jpg|jpeg|png)$/i, '-lg.$1');
}

function isSafeOnlineGame(rawGame: RawOnlineGame): boolean {
  const title = rawGame.title?.trim();
  const embed = rawGame.embed?.trim();
  const image = rawGame.image?.trim();
  if (!title || !embed || !image) return false;
  if (AD_HEAVY_GAME_IDS.has(slugify(title))) return false;
  if (!/^https:\/\//i.test(embed) || !/^https:\/\//i.test(image)) return false;

  try {
    const embedUrl = new URL(embed);
    const imageUrl = new URL(image);
    const embedHost = embedUrl.hostname.toLowerCase().replace(/^www\./, '');
    const imageHost = imageUrl.hostname.toLowerCase().replace(/^www\./, '');
    const embedPath = embedUrl.pathname.toLowerCase();
    const imagePath = imageUrl.pathname.toLowerCase();

    const trustedEmbedHost = embedHost === 'onlinegames.io' || embedHost === 'cloud.onlinegames.io';
    const trustedImageHost = imageHost === 'onlinegames.io' || imageHost === 'cloud.onlinegames.io';
    const blockedWrapper = embedPath.includes('index-og.html') || embedPath.includes('game-og.html');
    const usableImage = /\.(webp|png|jpe?g)$/i.test(imagePath) && !imagePath.includes('/placeholder');

    return trustedEmbedHost && trustedImageHost && !blockedWrapper && usableImage;
  } catch {
    return false;
  }
}

function onlineGameToGame(rawGame: RawOnlineGame): Game {
  const id = slugify(rawGame.title);
  const tags = parseTags(rawGame.tags || '');
  const rating = seededRating(id);
  const plays = seededPlays(id);
  const hasMobileTag = tags.some((tag) => tag.toLowerCase() === 'mobile');

  return {
    id,
    title: rawGame.title.trim(),
    category: inferCategory(tags),
    url: rawGame.embed.trim(),
    thumbnail: bestThumbnailVariant(rawGame.image),
    description: (rawGame.description || '').trim().slice(0, 500),
    rating,
    plays,
    authorUid: 'onlinegames-io',
    createdAt: '2026-06-04T15:51:40.314Z',
    isHot: plays > 500000,
    isTop: rating >= 4.7,
    tags,
    developer: 'OnlineGames.io',
    publisher: 'OnlineGames.io',
    mobileOptimization: hasMobileTag ? 'touch-friendly' : 'responsive',
    fullscreenSupport: true,
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-04T15:51:40.314Z',
    sourceId: 'onlinegames-io',
    avgPlayTime: '10m',
  };
}

function gamePixCategoryToTags(rawGame: RawGamePixGame): string[] {
  const category = rawGame.category ? titleCaseTag(rawGame.category.trim().toLowerCase()) : 'Arcade';
  const tags = new Set<string>(['Html5', 'Mobile', category]);
  if (/\b(shooter|battle|fighting|stickman)\b/i.test(category)) tags.add('Action');
  if (/\b(match|memory|puzzle|2048|ball)\b/i.test(category)) tags.add('Puzzle');
  if (/\b(car|driving|racing)\b/i.test(`${category} ${rawGame.title}`)) tags.add('Racing');
  if (/\b(sports|soccer|football|basket|penalty)\b/i.test(`${category} ${rawGame.title}`)) tags.add('Sports');
  return Array.from(tags);
}

function isSafeGamePixGame(rawGame: RawGamePixGame): boolean {
  const title = rawGame.title?.trim();
  const namespace = rawGame.namespace?.trim();
  const url = rawGame.url?.trim();
  const image = (rawGame.banner_image || rawGame.image || '').trim();
  if (!title || !namespace || !url || !image) return false;
  if (REMOVED_ORIGINAL_GAME_IDS.has(slugify(title)) || REMOVED_ORIGINAL_GAME_IDS.has(slugify(namespace))) return false;

  try {
    const gameUrl = new URL(url);
    const imageUrl = new URL(image);
    return gameUrl.protocol === 'https:' &&
      gameUrl.hostname.toLowerCase() === 'play.gamepix.com' &&
      gameUrl.pathname.endsWith('/embed') &&
      imageUrl.protocol === 'https:' &&
      imageUrl.hostname.toLowerCase() === 'img.gamepix.com';
  } catch {
    return false;
  }
}

function gamePixGameToGame(rawGame: RawGamePixGame): Game {
  const id = `gamepix-${slugify(rawGame.namespace || rawGame.title)}`;
  const tags = gamePixCategoryToTags(rawGame);
  const quality = typeof rawGame.quality_score === 'number' ? rawGame.quality_score : 0.75;
  const rating = Math.round((4.1 + Math.min(Math.max(quality, 0), 1) * 0.8) * 10) / 10;
  const plays = seededPlays(id);
  const orientation = rawGame.orientation === 'landscape' || rawGame.orientation === 'portrait' ? rawGame.orientation : 'any';

  return {
    id,
    title: rawGame.title.trim(),
    category: inferCategory(tags),
    url: rawGame.url.trim(),
    thumbnail: (rawGame.banner_image || rawGame.image || '').trim(),
    description: (rawGame.description || `${rawGame.title} is a fast-loading HTML5 game you can play instantly.`).trim().slice(0, 500),
    rating,
    plays,
    authorUid: 'gamepix',
    createdAt: rawGame.date_published || rawGame.date_modified || '2026-06-06T00:00:00.000Z',
    isHot: plays > 500000,
    isTop: rating >= 4.75,
    tags,
    developer: 'GamePix',
    publisher: 'GamePix',
    mobileOptimization: orientation === 'portrait' || orientation === 'any' ? 'touch-friendly' : 'responsive',
    fullscreenSupport: true,
    orientation,
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'gamepix',
    avgPlayTime: '8m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  };
}

async function fetchRawOnlineGames(url: string): Promise<RawOnlineGame[]> {
  const response = await fetch(url, { headers: { Accept: 'application/json' } });
  if (!response.ok) {
    throw new Error(`Could not load OnlineGames catalog: ${response.status}`);
  }

  const rawGames = await response.json();
  if (!Array.isArray(rawGames)) {
    throw new Error('OnlineGames catalog response was not an array.');
  }

  return rawGames as RawOnlineGame[];
}

async function fetchRawGamePixGames(url: string): Promise<RawGamePixGame[]> {
  const response = await fetch(url, { headers: { Accept: 'application/json' } });
  if (!response.ok) {
    throw new Error(`Could not load GamePix catalog: ${response.status}`);
  }

  const raw = await response.json();
  const items = Array.isArray(raw) ? raw : raw?.items;
  if (!Array.isArray(items)) {
    throw new Error('GamePix catalog response did not include an items array.');
  }

  return items as RawGamePixGame[];
}

async function fetchOnlineGamesRemote(): Promise<Game[]> {
  let rawGames: RawOnlineGame[];

  try {
    rawGames = await fetchRawOnlineGames(ONLINE_GAMES_API_URL);
  } catch {
    rawGames = await fetchRawOnlineGames(ONLINE_GAMES_SOURCE_URL);
  }

  return rawGames.filter(isSafeOnlineGame).map(onlineGameToGame);
}

async function fetchGamePixSourcePages(): Promise<RawGamePixGame[]> {
  const pages: RawGamePixGame[][] = [];

  for (let page = 1; page <= GAMEPIX_MAX_PAGES; page += 1) {
    const pageUrl = `${GAMEPIX_SOURCE_URL}?order=quality&page=${page}&pagination=${GAMEPIX_PAGE_SIZE}&sid=1`;
    const pageItems = await fetchRawGamePixGames(pageUrl);
    if (pageItems.length === 0) break;
    pages.push(pageItems);
    if (pages.flat().length >= GAMEPIX_TARGET_CATALOG_SIZE) break;
  }

  return pages.flat().slice(0, GAMEPIX_TARGET_CATALOG_SIZE);
}

async function fetchGamePixRemote(): Promise<Game[]> {
  let rawGames: RawGamePixGame[];

  try {
    rawGames = await fetchRawGamePixGames(GAMEPIX_API_URL);
  } catch {
    rawGames = await fetchGamePixSourcePages();
  }

  return rawGames.filter(isSafeGamePixGame).map(gamePixGameToGame);
}

export async function fetchOnlineGamesCatalog(): Promise<Game[]> {
  const [onlineGamesResult, gamePixResult] = await Promise.allSettled([
    fetchOnlineGamesRemote(),
    fetchGamePixRemote(),
  ]);

  const remoteGames = [
    ...(onlineGamesResult.status === 'fulfilled' ? onlineGamesResult.value : []),
    ...(gamePixResult.status === 'fulfilled' ? gamePixResult.value : []),
  ];

  if (onlineGamesResult.status === 'rejected' && gamePixResult.status === 'rejected') {
    throw onlineGamesResult.reason;
  }

  const seenIds = new Set<string>();
  return [...GAMES, ...remoteGames].filter((game) => {
    if (seenIds.has(game.id)) return false;
    seenIds.add(game.id);
    const normalizedId = slugify(game.id || game.title || '');
    const normalizedTitle = slugify(game.title || game.id || '');
    return !REMOVED_ORIGINAL_GAME_IDS.has(normalizedId) &&
      !REMOVED_ORIGINAL_GAME_IDS.has(normalizedTitle) &&
      !AD_HEAVY_GAME_IDS.has(game.id) &&
      !game.adsInjected &&
      !game.popupRisk &&
      !game.redirectRisk;
  }).slice(0, GAMEPIX_TARGET_CATALOG_SIZE);
}


export const GAMES: Game[] = [

  // ── Fighting Games (verified from catalog) ────────────────────────────
  {
    id: 'get-on-top',
    title: 'Get On Top',
    category: 'Fighting',
    url: 'https://www.onlinegames.io/games/2024/code/6/get-on-top/index.html',
    thumbnail: 'https://www.onlinegames.io/media/posts/697/responsive/Get-on-Top-lg.jpg',
    description: 'Two players wrestle to get on top! A hilarious 2-player physics fighting game — grab your opponent and pin them down to win. Great fun with a friend!',
    rating: 4.7,
    plays: 5800000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['2 Player', 'Fighting', 'Multiplayer', 'Action', 'Arcade', 'Physics', 'Fun'],
    developer: 'OnlineGames.io',
    publisher: 'OnlineGames.io',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '8m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'drunken-duel',
    title: 'Drunken Duel',
    category: 'Fighting',
    url: 'https://www.onlinegames.io/games/2024/code/2/drunken-duel/index.html',
    thumbnail: 'https://www.onlinegames.io/media/posts/698/responsive/Drunken-Duel-lg.jpg',
    description: 'The wobbly 2-player shooting duel! Control your drunk gunslinger and try to shoot your opponent before they get you. Hilarious physics make every match unpredictable.',
    rating: 4.6,
    plays: 4900000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['2 Player', 'Fighting', 'Multiplayer', 'Action', 'Arcade', 'Physics', 'Funny'],
    developer: 'OnlineGames.io',
    publisher: 'OnlineGames.io',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '8m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'tiny-crash-fighters',
    title: 'Tiny Crash Fighters',
    category: 'Fighting',
    url: 'https://www.onlinegames.io/games/2023/construct/285/tiny-crash-fighters/index.html',
    thumbnail: 'https://www.onlinegames.io/media/posts/622/responsive/Tiny-Crash-Fighters-lg.jpg',
    description: 'Build your robot and destroy the competition! Equip your machine with weapons and send it into the arena to battle. A fun auto-battler fighting game for all ages.',
    rating: 4.5,
    plays: 3200000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Fighting', 'Action', 'Arcade', 'Strategy', 'Mobile', 'Fun'],
    developer: 'OnlineGames.io',
    publisher: 'OnlineGames.io',
    mobileOptimization: 'touch-friendly',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '10m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'dark-ninja-hanjo',
    title: 'Dark Ninja Hanjo',
    category: 'Fighting',
    url: 'https://www.onlinegames.io/games/2023/unity/dark-ninja-hanjo/index.html',
    thumbnail: 'https://www.onlinegames.io/media/posts/451/responsive/Dark-Ninja-Hanjo-lg.jpg',
    description: 'Become the ultimate ninja warrior! Slash through enemies, dodge attacks and master stealth combat as the legendary Dark Ninja Hanjo in this action-packed 3D fighting game.',
    rating: 4.6,
    plays: 4100000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Fighting', 'Action', 'Adventure', '1 Player', 'Ninja', '3d'],
    developer: 'OnlineGames.io',
    publisher: 'OnlineGames.io',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '12m',
    contentRating: 'Teen',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  // ── Bus / Transport Games (verified from catalog) ──────────────────────
  {
    id: 'bus-subway-runner',
    title: 'Bus Subway Runner',
    category: 'Arcade',
    url: 'https://www.onlinegames.io/games/2022/unity/bus-subway-runner/index.html',
    thumbnail: 'https://www.onlinegames.io/media/posts/235/responsive/Bus-Subway-Runner-Game-lg.jpg',
    description: 'Run from the police on top of speeding buses! Dodge obstacles, collect coins and survive as long as you can in this wild Subway Surfer-style endless runner — with buses!',
    rating: 4.5,
    plays: 3800000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Arcade', 'Action', '1 Player', 'Mobile', 'Running', 'Skill', 'Fun'],
    developer: 'OnlineGames.io',
    publisher: 'OnlineGames.io',
    mobileOptimization: 'touch-friendly',
    fullscreenSupport: true,
    orientation: 'portrait',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '8m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'taxi-simulator',
    title: 'Taxi Simulator',
    category: 'Simulator',
    url: 'https://www.onlinegames.io/games/2022/unity/taxi-simulator/index.html',
    thumbnail: 'https://www.onlinegames.io/media/posts/465/responsive/Taxi-Simulator-lg.jpg',
    description: 'Pick up passengers and get them to their destinations on time! Navigate busy city streets in your taxi and earn cash in this realistic driving simulator.',
    rating: 4.4,
    plays: 2600000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Simulator', 'Driving', '1 Player', '3d', 'Car'],
    developer: 'OnlineGames.io',
    publisher: 'OnlineGames.io',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '10m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'truck-racing',
    title: 'Truck Racing',
    category: 'Racing',
    url: 'https://www.onlinegames.io/games/2022/construct/144/truck-racing/index.html',
    thumbnail: 'https://www.onlinegames.io/media/posts/712/responsive/Truck-Racing-lg.jpg',
    description: 'Race massive trucks at full speed! Overtake rivals, avoid crashes and cross the finish line first in this fast-paced 2D truck racing game with great mobile support.',
    rating: 4.4,
    plays: 2300000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Racing', '1 Player', 'Mobile', '2d', 'Car', 'Truck', 'Fun'],
    developer: 'OnlineGames.io',
    publisher: 'OnlineGames.io',
    mobileOptimization: 'touch-friendly',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '8m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'monster-truck-city-parking',
    title: 'Monster Truck City Parking',
    category: 'Simulator',
    url: 'https://www.onlinegames.io/games/2021/unity/monster-truck-city-parking/index.html',
    thumbnail: 'https://www.onlinegames.io/media/posts/582/responsive/Monster-Truck-City-Parking-lg.jpg',
    description: 'Park a massive monster truck through tight city spaces! Navigate obstacles, reverse park and complete each level without crashing in this challenging 3D parking game.',
    rating: 4.3,
    plays: 1900000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Simulator', 'Driving', '1 Player', '3d', 'Truck', 'Skill'],
    developer: 'OnlineGames.io',
    publisher: 'OnlineGames.io',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '8m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  // ── Airplane / Flight Games (verified from catalog) ────────────────────
  {
    id: 'real-flight-simulator',
    title: 'Real Flight Simulator',
    category: 'Simulator',
    url: 'https://cloud.onlinegames.io/games/2023/unity2/real-flight-simulator/index.html',
    thumbnail: 'https://www.onlinegames.io/media/posts/342/responsive/Real-Flight-Simulator-2-lg.jpg',
    description: 'Take to the skies in a real passenger jet! Master takeoff, cruising altitude, and landing at airports around the world in this immersive 3D flight simulator.',
    rating: 4.6,
    plays: 4500000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Simulator', '1 Player', '3d', 'Airplane', 'Flying', 'Skill'],
    developer: 'OnlineGames.io',
    publisher: 'OnlineGames.io',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '12m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'airplane-racer',
    title: 'Airplane Racer',
    category: 'Racing',
    url: 'https://www.onlinegames.io/games/2022/unity/airplane-racer/index.html',
    thumbnail: 'https://www.onlinegames.io/media/posts/268/responsive/Airplane-Racer-lg.jpg',
    description: 'Race planes through the sky solo or against a friend! Choose your aircraft, pick a track and battle through aerial courses in this vivid 3D airplane racing game.',
    rating: 4.5,
    plays: 3700000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Racing', '2 Player', 'Multiplayer', '3d', 'Airplane', 'Flying', 'Action'],
    developer: 'OnlineGames.io',
    publisher: 'OnlineGames.io',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '10m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'alien-sky-invasion',
    title: 'Alien Sky Invasion',
    category: 'Action',
    url: 'https://www.onlinegames.io/games/2021/unity3/alien-sky-invasion/index.html',
    thumbnail: 'https://www.onlinegames.io/media/posts/594/responsive/Alien-Sky-Invasion-lg.jpg',
    description: 'Aliens are invading from the sky! Pilot your fighter plane and blast wave after wave of alien aircraft before they destroy the planet. Fast-paced 3D aerial shooting action.',
    rating: 4.5,
    plays: 3400000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Action', 'Shooting', '1 Player', '3d', 'Airplane', 'Flying', 'Space'],
    developer: 'OnlineGames.io',
    publisher: 'OnlineGames.io',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '10m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'rescue-helicopter',
    title: 'Rescue Helicopter',
    category: 'Simulator',
    url: 'https://www.onlinegames.io/games/2021/2/rescue-helicopter/index.html',
    thumbnail: 'https://www.onlinegames.io/media/posts/468/responsive/Rescue-Helicopter-lg.jpg',
    description: 'Fly rescue missions in your helicopter! Pick up injured patients and deliver them to the hospital safely. A fun mobile-friendly helicopter flying game for all ages.',
    rating: 4.4,
    plays: 2900000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Simulator', '1 Player', 'Mobile', 'Flying', 'Helicopter', '2d'],
    developer: 'OnlineGames.io',
    publisher: 'OnlineGames.io',
    mobileOptimization: 'touch-friendly',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '8m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'hover-racer-pro',
    title: 'Hover Racer Pro',
    category: 'Racing',
    url: 'https://www.onlinegames.io/games/2021/unity/hover-racer-pro/index.html',
    thumbnail: 'https://www.onlinegames.io/media/posts/572/responsive/Hover-Racer-Pro-lg.jpg',
    description: 'Race futuristic hover vehicles through incredible tracks! Speed through twisting courses, hit turbo boosts, and leave rivals in the dust in this 3D sci-fi racing game.',
    rating: 4.5,
    plays: 3100000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Racing', '1 Player', '3d', 'Flying', 'Airplane', 'Sci-Fi', 'Speed'],
    developer: 'OnlineGames.io',
    publisher: 'OnlineGames.io',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '10m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },


  // ── Fireboy and Watergirl Series (verified working embeds) ───────────
  {
    id: 'fbw-1-forest-temple',
    title: 'Fireboy and Watergirl 1: Forest Temple',
    category: 'Adventure',
    url: 'https://www.fireboyandwatergirl-unblocked.com/',
    thumbnail: 'https://www.fireboyandwatergirl-unblocked.com/Play-Fireboy-%26-Watergirl-Online-For-Free.webp',
    description: 'The classic co-op adventure! Guide Fireboy and Watergirl through the Forest Temple, solving puzzles and avoiding hazards. One of the most beloved 2-player platformers ever made.',
    rating: 4.9,
    plays: 12000000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: true,
    tags: ['2 Player', 'Multiplayer', 'Adventure', 'Puzzle', 'Platformer', 'Co-Op'],
    developer: 'Oslo Albet',
    publisher: 'fireboyandwatergirl-unblocked.com',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '20m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'fbw-2-light-temple',
    title: 'Fireboy and Watergirl 2: Light Temple',
    category: 'Adventure',
    url: 'https://kiz10.com/embed/fireboy-and-watergirl-2-light-temple/',
    thumbnail: 'https://cdn.kiz10.com/upload/thumbnails/10139/1530728487_fireboy-and-watergirl-2-light-temple.webp',
    description: 'Fireboy and Watergirl return to the Light Temple! Use mirrors and prisms to direct laser beams, solve new puzzles and reach the exit doors together in this brilliant sequel.',
    rating: 4.8,
    plays: 9500000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['2 Player', 'Multiplayer', 'Adventure', 'Puzzle', 'Platformer', 'Co-Op'],
    developer: 'Oslo Albet',
    publisher: 'Kiz10',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '20m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'fbw-3-ice-temple',
    title: 'Fireboy and Watergirl 3: Ice Temple',
    category: 'Adventure',
    url: 'https://www.gameflare.com/embed/fireboy-and-watergirl-3-ice-temple/',
    thumbnail: 'https://data.gameflare.com/games/2505/Rhf108I10eNNy1-400-300.jpg',
    description: 'Enter the frozen Ice Temple! Slide across icy floors, push blocks and work together to beat every chilly puzzle level. The third thrilling chapter of the FBW series.',
    rating: 4.8,
    plays: 8200000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['2 Player', 'Multiplayer', 'Adventure', 'Puzzle', 'Platformer', 'Co-Op'],
    developer: 'Oslo Albet',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '20m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'fbw-4-crystal-temple',
    title: 'Fireboy and Watergirl 4: Crystal Temple',
    category: 'Adventure',
    url: 'https://www.gameflare.com/embed/fireboy-and-watergirl-4/',
    thumbnail: 'https://data.gameflare.com/games/3738/tHxnLsjKqwPQVR-400-300.jpg',
    description: 'Explore the Crystal Temple! Collect crystals, navigate tricky platforms and use teleports to solve mind-bending co-op puzzles in the fourth Fireboy and Watergirl adventure.',
    rating: 4.8,
    plays: 7800000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['2 Player', 'Multiplayer', 'Adventure', 'Puzzle', 'Platformer', 'Co-Op'],
    developer: 'Oslo Albet',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '20m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  {
    id: 'fbw-5-elements',
    title: 'Fireboy and Watergirl 5: Elements',
    category: 'Adventure',
    url: 'https://www.gameflare.com/embed/fireboy-and-watergirl-5-elements/',
    thumbnail: 'https://data.gameflare.com/games/8903/e1ghf5rBo6lgTK-400-300.jpg',
    description: 'The elements come alive! Master fire, water, air and earth powers to solve complex puzzles across four uniquely themed temples. The fifth legendary FBW chapter.',
    rating: 4.8,
    plays: 6900000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['2 Player', 'Multiplayer', 'Adventure', 'Puzzle', 'Platformer', 'Co-Op'],
    developer: 'Oslo Albet',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '20m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'fbw-6-fairy-tales',
    title: 'Fireboy and Watergirl 6: Fairy Tales',
    category: 'Adventure',
    url: 'https://www.gameflare.com/embed/fireboy-and-watergirl-6-fairy-tales/',
    thumbnail: 'https://data.gameflare.com/games/9674/STQTxmN81yso42-400-300.jpg',
    description: 'Enter a magical fairy tale world! Solve enchanting new puzzles with moving platforms, coloured portals and mystical powers in the sixth installment of the beloved FBW saga.',
    rating: 4.8,
    plays: 6100000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['2 Player', 'Multiplayer', 'Adventure', 'Puzzle', 'Platformer', 'Co-Op'],
    developer: 'Oslo Albet',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '20m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'fbw-7-and-friends',
    title: 'Fireboy and Watergirl 7 & Friends',
    category: 'Adventure',
    url: 'https://www.gameflare.com/embed/fireboy-and-watergirl-7-and-friends/',
    thumbnail: 'https://data.gameflare.com/games/11332/l7QkoGaNVKf62M-400-300.jpg',
    description: 'Now with more characters! Play as Fireboy, Watergirl and their friends to tackle brand new co-op puzzles. The latest and most feature-rich chapter of the legendary series.',
    rating: 4.8,
    plays: 4800000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['2 Player', 'Multiplayer', 'Adventure', 'Puzzle', 'Platformer', 'Co-Op'],
    developer: 'Oslo Albet',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '20m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  // ── Action / Open World (verified Gameflare embeds) ──────────────────
  {
    id: 'five-nights-at-epsteins',
    title: "Five Nights at Epstein's",
    category: 'Horror',
    url: "https://www.gameflare.com/embed/five-nights-at-epstein-s/",
    thumbnail: 'https://data.gameflare.com/games/11242/mtwNEEJpnafK45-400-300.jpg',
    description: 'Survive five terrifying nights! Monitor the cameras, manage your power and survive until 6am in this suspenseful horror game inspired by the classic FNAF formula.',
    rating: 4.6,
    plays: 5400000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Horror', 'Action', '1 Player', 'Scary', 'Survival', 'Puzzle'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '12m',
    contentRating: 'Teen',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'dude-theft-wars',
    title: 'Dude Theft Wars',
    category: 'Action',
    url: 'https://www.gameflare.com/embed/dude-theft-wars/',
    thumbnail: 'https://data.gameflare.com/games/10213/fhAdRFc7QwzPpc-400-300.jpg',
    description: 'The ultimate open-world chaos game! Drive cars, start fights, blow things up and cause mayhem across a huge city. Think GTA in your browser — completely unhinged sandbox fun.',
    rating: 4.7,
    plays: 13000000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: true,
    tags: ['Action', 'Sandbox', '1 Player', 'Open World', 'Driving', 'Funny'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '20m',
    contentRating: 'Teen',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  // ── Girls Games (verified Gameflare embeds) ───────────────────────────
  {
    id: 'shopaholic-hollywood',
    title: 'Shopaholic Hollywood',
    category: 'Girls',
    url: 'https://www.gameflare.com/embed/shopaholic-hollywood/',
    thumbnail: 'https://data.gameflare.com/games/4229/w2M8pz9yB3j37n-400-300.jpg',
    description: 'Shop like a Hollywood star! Pick the perfect outfits, accessories and looks across the most glamorous boutiques on the boulevard. Fashion, fun and celebrity style.',
    rating: 4.3,
    plays: 5800000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Girls', 'Casual', '1 Player', 'Fashion', 'Shopping', 'Dress Up'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '10m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'shopaholic-new-york',
    title: 'Shopaholic New York',
    category: 'Girls',
    url: 'https://www.gameflare.com/embed/shopaholic-new-york/',
    thumbnail: 'https://data.gameflare.com/games/5928/YOn9nfejSNnQy5-400-300.jpg',
    description: 'Hit the New York shops and find the best deals before time runs out! Grab clothes, shoes and accessories in the city that never sleeps.',
    rating: 4.3,
    plays: 6200000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Girls', 'Casual', '1 Player', 'Fashion', 'Shopping', 'Dress Up'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '10m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'shopaholic-tokyo',
    title: 'Shopaholic Tokyo',
    category: 'Girls',
    url: 'https://www.gameflare.com/embed/shopaholic-tokyo/',
    thumbnail: 'https://data.gameflare.com/games/6249/Hegnr4EC2dlrhU-400-300.jpg',
    description: 'Explore the colourful fashion districts of Tokyo! Shop for kawaii outfits, accessories and trendy Japanese streetwear in this fun shopping spree game.',
    rating: 4.4,
    plays: 5400000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Girls', 'Casual', '1 Player', 'Fashion', 'Shopping', 'Dress Up'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '10m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'shopaholic-hawaii',
    title: 'Shopaholic Hawaii',
    category: 'Girls',
    url: 'https://www.gameflare.com/embed/shopaholic-hawaii/',
    thumbnail: 'https://data.gameflare.com/games/6633/9rquV2fCDb7qaw-400-300.jpg',
    description: 'Shop in paradise! Browse tropical boutiques in Hawaii and find the perfect beach outfits, sunglasses and accessories for your island getaway look.',
    rating: 4.3,
    plays: 4900000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Girls', 'Casual', '1 Player', 'Fashion', 'Shopping', 'Dress Up'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '10m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  // ── Horror Games (verified Gameflare embeds) ──────────────────────────
  {
    id: 'subway-horror-chapter-1',
    title: 'Subway Horror: Chapter 1',
    category: 'Horror',
    url: 'https://www.gameflare.com/embed/subway-horror-chapter-1/',
    thumbnail: 'https://data.gameflare.com/games/10482/9tGlpxlG8V8SJ2-400-300.jpg',
    description: 'Trapped in an abandoned subway, you must survive the darkness and whatever lurks within. A chilling first-person horror experience that will keep you on edge.',
    rating: 4.5,
    plays: 3200000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Horror', '1 Player', 'Scary', 'Survival', '3D'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '15m',
    contentRating: 'Teen',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'horror-nun',
    title: 'Horror Nun',
    category: 'Horror',
    url: 'https://www.gameflare.com/embed/horror-nun/',
    thumbnail: 'https://data.gameflare.com/games/11212/caOhUXF0V75k2h-400-300.jpg',
    description: 'Escape from the terrifying Horror Nun! Sneak through the house, solve puzzles and avoid the sinister figure that hunts you. One wrong move and she catches you.',
    rating: 4.6,
    plays: 4800000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Horror', '1 Player', 'Scary', 'Survival', 'Stealth'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '15m',
    contentRating: 'Teen',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'granny',
    title: 'Granny',
    category: 'Horror',
    url: 'https://www.gameflare.com/embed/granny/',
    thumbnail: 'https://data.gameflare.com/games/10467/nvi21wPoJ0WvIa-400-300.jpg',
    description: 'Granny keeps you locked in her house. Escape in 5 days without making noise or she will hear you. One of the most iconic mobile horror games, now in your browser.',
    rating: 4.7,
    plays: 21000000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: true,
    isTop: true,
    tags: ['Horror', '1 Player', 'Scary', 'Survival', 'Stealth', 'Puzzle'],
    developer: 'DVloper',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '20m',
    contentRating: 'Teen',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'granny-4',
    title: 'Granny 4',
    category: 'Horror',
    url: 'https://www.gameflare.com/embed/granny-4/',
    thumbnail: 'https://data.gameflare.com/games/11209/S7msWhXol2tBmt-400-300.jpg',
    description: 'The iconic horror grandma is back and scarier than ever. New traps, new secrets and a bigger house to escape from. Can you survive all 5 days this time?',
    rating: 4.7,
    plays: 8900000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Horror', '1 Player', 'Scary', 'Survival', 'Stealth', 'Puzzle'],
    developer: 'DVloper',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '20m',
    contentRating: 'Teen',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  // ── Simulator / Driving Games (verified Gameflare embeds) ─────────────
  {
    id: 'bus-parking-simulator',
    title: 'Bus Parking Simulator',
    category: 'Simulator',
    url: 'https://www.gameflare.com/embed/bus-parking-simulator/',
    thumbnail: 'https://data.gameflare.com/games/9006/Vj403imCKISuzs-400-300.jpg',
    description: 'Take the wheel of a real bus and park it perfectly in tight spots. Realistic controls, multiple levels and increasingly challenging parking scenarios to master.',
    rating: 4.3,
    plays: 2700000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Simulator', '1 Player', 'Driving', '3D', 'Parking', 'Casual'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '15m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'bus-simulator-3d',
    title: 'Bus Simulator 3D',
    category: 'Simulator',
    url: 'https://www.gameflare.com/embed/bus-simulator-3d/',
    thumbnail: 'https://data.gameflare.com/games/11037/FttQkQlmUu3spD-400-300.jpg',
    description: 'Drive a full-size bus through city streets, pick up passengers and follow your route on time. A detailed 3D driving simulator with realistic traffic and physics.',
    rating: 4.4,
    plays: 3500000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Simulator', '1 Player', 'Driving', '3D', 'City', 'Casual'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '20m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'driving-school-simulator',
    title: 'Driving School Simulator',
    category: 'Simulator',
    url: 'https://www.gameflare.com/embed/driving-school-simulator/',
    thumbnail: 'https://data.gameflare.com/games/11307/OKWip6IKlO1mGm-400-300.jpg',
    description: 'Learn to drive the right way! Complete driving lessons, pass tests and navigate real traffic in this detailed driving school simulator. Great for practicing road rules.',
    rating: 4.4,
    plays: 2900000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Simulator', '1 Player', 'Driving', '3D', 'Educational', 'Casual'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '20m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'truck-simulator-european-roads',
    title: 'Truck Simulator: European Roads',
    category: 'Simulator',
    url: 'https://www.gameflare.com/embed/truck-simulator-european-roads/',
    thumbnail: 'https://data.gameflare.com/games/11320/k3C3hBIcGNEbNH-400-300.jpg',
    description: 'Haul cargo across stunning European highways in a massive truck. Realistic physics, long-haul routes and scenic roads make this a top-tier trucking simulator.',
    rating: 4.5,
    plays: 4100000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Simulator', '1 Player', 'Driving', '3D', 'Truck', 'Casual'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '20m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'truck-simulator-pro-2',
    title: 'Truck Simulator Pro 2',
    category: 'Simulator',
    url: 'https://www.gameflare.com/embed/truck-simulator-pro-2/',
    thumbnail: 'https://data.gameflare.com/games/11303/X8KvWhKySll71t-400-300.jpg',
    description: 'The ultimate truck driving experience! Upgrade your rig, take on long-haul contracts and conquer challenging terrain across a massive open world.',
    rating: 4.6,
    plays: 5200000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Simulator', '1 Player', 'Driving', '3D', 'Truck', 'Open World'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '25m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'truck-simulator-europe',
    title: 'Truck Simulator: Europe',
    category: 'Simulator',
    url: 'https://www.gameflare.com/embed/truck-simulator-europe/',
    thumbnail: 'https://data.gameflare.com/games/11253/XH95DRcQFefxt5-400-300.jpg',
    description: 'Drive across Europe delivering goods between cities. Fuel up, manage your time and navigate highways, tunnels and mountain passes in this satisfying truck sim.',
    rating: 4.5,
    plays: 3800000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Simulator', '1 Player', 'Driving', '3D', 'Truck', 'Casual'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '20m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'real-construction-excavator-simulator',
    title: 'Real Construction Excavator Simulator',
    category: 'Simulator',
    url: 'https://www.gameflare.com/embed/real-construction-excavator-simulator/',
    thumbnail: 'https://data.gameflare.com/games/10232/PqWmGTAkFAS7kL-400-300.jpg',
    description: 'Operate a massive excavator on a real construction site. Dig, scoop and move earth with realistic controls in this satisfying heavy machinery simulator.',
    rating: 4.3,
    plays: 2100000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Simulator', '1 Player', '3D', 'Construction', 'Casual'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '15m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'russian-uaz-offroad-driving-3d',
    title: 'Russian UAZ Offroad Driving 3D',
    category: 'Simulator',
    url: 'https://www.gameflare.com/embed/russian-uaz-offroad-driving-3d/',
    thumbnail: 'https://data.gameflare.com/games/7529/UfVV0jobtYqMcr-400-300.jpg',
    description: 'Take the legendary Russian UAZ 4x4 through brutal off-road terrain. Mud, rocks, rivers and forest tracks — push this iconic vehicle to its absolute limits.',
    rating: 4.4,
    plays: 3300000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Simulator', '1 Player', 'Driving', '3D', 'Offroad', 'Casual'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '15m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'russian-offroad-pickup-drive',
    title: 'Russian Offroad Pickup Drive',
    category: 'Simulator',
    url: 'https://www.gameflare.com/embed/russian-offroad-pickup-drive/',
    thumbnail: 'https://data.gameflare.com/games/7448/DYvhzTwblZv3c2-400-300.jpg',
    description: 'Drive a rugged Russian pickup truck across wild off-road landscapes. Mud bogs, steep hills and river crossings test your driving skills in this open-world offroad sim.',
    rating: 4.4,
    plays: 2900000,
    authorUid: 'curated',
    createdAt: '2026-06-07T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Simulator', '1 Player', 'Driving', '3D', 'Offroad', 'Open World'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-07T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '15m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  // ── Hole.io Games (verified Gameflare embeds) ─────────────────────────
  {
    id: 'holeio',
    title: 'Hole.io',
    category: 'Casual',
    url: 'https://www.gameflare.com/embed/holeio/',
    thumbnail: 'https://data.gameflare.com/games/8614/35w8JBDgRymodd-400-300.jpg',
    description: 'You are a black hole in the city! Swallow everything in your path — cars, people, buildings — and grow bigger to consume even larger objects. Compete against other holes to be the biggest!',
    rating: 4.8,
    plays: 22000000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: true,
    tags: ['Casual', 'Arcade', 'Multiplayer', 'io', 'Fun', 'Mobile'],
    developer: 'Voodoo',
    publisher: 'Gameflare',
    mobileOptimization: 'touch-friendly',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '10m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'hole-arena',
    title: 'Hole Arena',
    category: 'Casual',
    url: 'https://www.gameflare.com/embed/hole-arena/',
    thumbnail: 'https://data.gameflare.com/games/11316/rr2aIj8fUKyrVx-400-300.jpg',
    description: 'Battle rival holes in an epic arena! Swallow objects to grow bigger, then take down your opponents before the timer runs out. A chaotic and addictive io-style arena brawler.',
    rating: 4.6,
    plays: 8500000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Casual', 'Arcade', 'Multiplayer', 'io', 'Fun', 'Mobile'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'touch-friendly',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '8m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  // ── Fighting (verified Gameflare embeds) ──────────────────────────────
  {
    id: 'tekken-3',
    title: 'Tekken 3',
    category: 'Fighting',
    url: 'https://www.gameflare.com/embed/tekken-3/',
    thumbnail: 'https://data.gameflare.com/games/7027/6BmAnPQOB5JJaV-400-300.jpg',
    description: 'The legendary fighting game is here! Choose from 23 iconic fighters and battle through the King of Iron Fist Tournament. One of the greatest arcade fighters ever made — now in your browser.',
    rating: 4.9,
    plays: 18000000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: true,
    tags: ['Fighting', 'Action', '2 Player', 'Multiplayer', 'Arcade', 'Classic'],
    developer: 'Namco',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '15m',
    contentRating: 'Teen',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  // ── Bus / Transport (verified Gameflare embeds) ────────────────────────
  {
    id: 'bus-simulator-evo',
    title: 'Bus Simulator Evo',
    category: 'Simulator',
    url: 'https://www.gameflare.com/embed/bus-simulator-evo/',
    thumbnail: 'https://data.gameflare.com/games/11321/hNwf93VkswTk26-400-300.jpg',
    description: 'Drive a real city bus and pick up passengers on time! Navigate busy roads, follow your route and keep riders happy in this detailed 3D bus driving simulator.',
    rating: 4.6,
    plays: 5200000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Simulator', 'Driving', '1 Player', '3d', 'Bus'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '12m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'bus-simulator-3d',
    title: 'Bus Simulator 3D',
    category: 'Simulator',
    url: 'https://www.gameflare.com/embed/bus-simulator-3d/',
    thumbnail: 'https://data.gameflare.com/games/11037/FttQkQlmUu3spD-400-300.jpg',
    description: 'Take the wheel of a full-size city bus! Pick up passengers, follow the route map, and deliver everyone safely in this immersive 3D bus simulation game.',
    rating: 4.5,
    plays: 4100000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Simulator', 'Driving', '1 Player', '3d', 'Bus'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '12m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  // ── Airplane / Flight (verified Gameflare embeds) ──────────────────────
  {
    id: 'flight-simulator-flywings-2016',
    title: 'Flight Simulator FlyWings 2016',
    category: 'Simulator',
    url: 'https://www.gameflare.com/embed/flight-simulator-flywings-2016/',
    thumbnail: 'https://data.gameflare.com/games/6962/dIXaGzDXruQMAC-400-300.jpg',
    description: 'A stunning realistic flight simulator! Pilot real aircraft across beautiful landscapes, manage cockpit instruments and master the art of flying in this detailed sim.',
    rating: 4.6,
    plays: 6300000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Simulator', '1 Player', '3d', 'Airplane', 'Flying', 'Skill'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '15m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'airplane-flight-simulator-evo',
    title: 'Airplane Flight Simulator Evo',
    category: 'Simulator',
    url: 'https://www.gameflare.com/embed/airplane-flight-simulator-evo/',
    thumbnail: 'https://data.gameflare.com/games/11290/bA5iFi1QgjbPaR-400-300.jpg',
    description: 'The ultimate airplane simulation experience! Take off from real airports, fly through stunning skies and land with precision in this next-level 3D flight simulator.',
    rating: 4.6,
    plays: 4700000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Simulator', '1 Player', '3d', 'Airplane', 'Flying', 'Skill'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '12m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  // ── Casual / Arcade (verified Gameflare embeds) ────────────────────────
  {
    id: 'angry-birds-space-hd',
    title: 'Angry Birds Space HD',
    category: 'Casual',
    url: 'https://www.gameflare.com/embed/angry-birds-space-hd/',
    thumbnail: 'https://data.gameflare.com/games/3038/MDGwNz60XhvlCq-400-300.jpg',
    description: 'The Angry Birds are in space! Use gravity and clever physics to launch birds around planets and smash the pigs hiding in galactic structures. Out-of-this-world fun for all ages.',
    rating: 4.7,
    plays: 14000000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: true,
    tags: ['Casual', 'Arcade', 'Puzzle', '1 Player', 'Mobile', 'Physics', 'Fun', 'Kids'],
    developer: 'Rovio',
    publisher: 'Gameflare',
    mobileOptimization: 'touch-friendly',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '12m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'geometry-dash-super-editor',
    title: 'Geometry Dash Super Editor',
    category: 'Platformer',
    url: 'https://www.gameflare.com/embed/geometry-dash-super-editor/',
    thumbnail: 'https://data.gameflare.com/games/10960/GGVV3M1NVoifCn-400-300.jpg',
    description: 'The Geometry Dash you love, now with a level editor! Jump and fly through insane rhythm-based obstacles, create your own levels and challenge the world. Pure reflex gaming.',
    rating: 4.7,
    plays: 9200000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Platformer', 'Arcade', 'Action', '1 Player', 'Music', 'Skill', 'Rhythm'],
    developer: 'RobTop Games',
    publisher: 'Gameflare',
    mobileOptimization: 'touch-friendly',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '10m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'geometry-vibes-x-arrow',
    title: 'Geometry Vibes X Arrow',
    category: 'Platformer',
    url: 'https://www.gameflare.com/embed/geometry-vibes-x-arrow/',
    thumbnail: 'https://data.gameflare.com/games/11143/0WF9yoGgxS1Eca-400-300.jpg',
    description: 'A fresh take on geometry-style runners! Dodge spikes, flip gravity and survive neon-lit obstacle courses in this slick rhythm platformer with vibrant visuals and addictive gameplay.',
    rating: 4.5,
    plays: 3800000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Platformer', 'Arcade', 'Action', '1 Player', 'Skill', 'Rhythm'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'touch-friendly',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '8m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  // ── Sports / Football (verified Gameflare embeds) ─────────────────────
  {
    id: 'football-legends-2026',
    title: 'Football Legends 2026',
    category: 'Sports',
    url: 'https://www.gameflare.com/embed/football-legends-2026/',
    thumbnail: 'https://data.gameflare.com/games/11337/Lv0ZSrgiRGCjuO-400-300.jpg',
    description: 'The ultimate football legends showdown! Pick your star player and compete in fast-paced 1v1 or 2-player football matches. Skill moves, power shots and epic saves await.',
    rating: 4.7,
    plays: 9800000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: true,
    tags: ['Sports', 'Football', '2 Player', 'Multiplayer', 'Arcade', 'Fun'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '10m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'big-head-football',
    title: 'Big Head Football',
    category: 'Sports',
    url: 'https://www.gameflare.com/embed/big-head-football/',
    thumbnail: 'https://data.gameflare.com/games/3396/hu0fhis7OSe6KP-400-300.jpg',
    description: 'Play football with huge bobblehead players! Choose your national team and face off in hilarious 1v1 matches with oversized heads and comical physics. Great 2-player fun!',
    rating: 4.6,
    plays: 7400000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Sports', 'Football', '2 Player', 'Multiplayer', 'Arcade', 'Funny'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '8m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'football-world-cup-2019',
    title: 'Football World Cup',
    category: 'Sports',
    url: 'https://www.gameflare.com/embed/football-world-cup-2019/',
    thumbnail: 'https://data.gameflare.com/games/8973/pWXlJv2QCT8Ugn-400-300.jpg',
    description: 'Lead your country to World Cup glory! Compete through group stages and knockouts in this action-packed football tournament game. Dribble, shoot and save your way to the trophy.',
    rating: 4.5,
    plays: 5200000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Sports', 'Football', '1 Player', 'Arcade', 'Tournament'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '12m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  // ── Racing (verified Gameflare embeds) ────────────────────────────────
  {
    id: 'street-racing-3d',
    title: 'Street Racing 3D',
    category: 'Racing',
    url: 'https://www.gameflare.com/embed/street-racing-3d/',
    thumbnail: 'https://data.gameflare.com/games/11372/t7G83DVHWVQ76k-400-300.jpg',
    description: 'Hit the streets in a high-performance car! Weave through traffic, hit nitro boosts and outrun rivals in this slick 3D street racing game with stunning visuals.',
    rating: 4.6,
    plays: 6100000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Racing', '1 Player', '3d', 'Car', 'Speed', 'Skill'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '10m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  // ── Fighting / Action (verified Gameflare embeds) ─────────────────────
  {
    id: 'shadow-fight-2',
    title: 'Shadow Fight 2',
    category: 'Fighting',
    url: 'https://www.gameflare.com/embed/shadow-fight-2/',
    thumbnail: 'https://data.gameflare.com/games/11350/YeC3ga4MqRK41g-400-300.jpg',
    description: 'The legendary shadow fighting RPG! Equip deadly weapons, learn powerful combat skills and defeat ruthless bosses in this stunning silhouette fighting game.',
    rating: 4.8,
    plays: 15000000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: true,
    tags: ['Fighting', 'Action', 'Adventure', '1 Player', 'RPG', 'Skill'],
    developer: 'Nekki',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '20m',
    contentRating: 'Teen',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'stick-hero-battle-legacy',
    title: 'Stick Hero Battle Legacy',
    category: 'Fighting',
    url: 'https://www.gameflare.com/embed/stick-hero-battle-legacy/',
    thumbnail: 'https://data.gameflare.com/games/11374/qus0i9rZhrsnax-400-300.jpg',
    description: 'Become the ultimate stick hero! Battle through waves of enemies using fluid combat moves, unlock new skills and defeat powerful bosses in this action-packed stickman fighter.',
    rating: 4.5,
    plays: 4300000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Fighting', 'Action', '1 Player', 'Stickman', 'Arcade'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '12m',
    contentRating: 'Teen',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'samurai-warrior',
    title: 'Samurai Warrior',
    category: 'Fighting',
    url: 'https://www.gameflare.com/embed/samurai-warrior/',
    thumbnail: 'https://data.gameflare.com/games/9489/rNmazeTGaZkH3g-400-300.jpg',
    description: 'Become a legendary samurai and cut down all who stand in your way! Slash through hordes of enemies with precise sword combos in this intense action fighter.',
    rating: 4.6,
    plays: 5700000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Fighting', 'Action', '1 Player', 'Samurai', 'Sword', 'Arcade'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '12m',
    contentRating: 'Teen',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'the-patriots-revolution',
    title: 'The Patriots Revolution',
    category: 'Action',
    url: 'https://www.gameflare.com/embed/the-patriots-revolution/',
    thumbnail: 'https://data.gameflare.com/games/11371/FcB9Yo230qM5xb-400-300.jpg',
    description: 'Lead the revolution against tyranny! Fight through intense battlefield missions, command your troops and battle enemy forces in this action-packed war game.',
    rating: 4.5,
    plays: 3900000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Action', 'Shooting', '1 Player', 'War', 'Strategy'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '12m',
    contentRating: 'Teen',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'prison-break',
    title: 'Prison Break',
    category: 'Adventure',
    url: 'https://www.gameflare.com/embed/prison-break/',
    thumbnail: 'https://data.gameflare.com/games/9476/L2ETMWRHgpcyaN-400-300.jpg',
    description: 'Escape from maximum security prison! Sneak past guards, pick locks, find hidden passages and outwit the warden in this thrilling stealth escape adventure.',
    rating: 4.6,
    plays: 6800000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Adventure', 'Action', '1 Player', 'Stealth', 'Puzzle', 'Escape'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '15m',
    contentRating: 'Teen',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  // ── Obby / Platformer (verified Gameflare embeds) ──────────────────────
  {
    id: 'obby-1-jump-power-every-second',
    title: 'Obby: 1 Jump Power Every Second',
    category: 'Platformer',
    url: 'https://www.gameflare.com/embed/obby-1-jump-power-every-second/',
    thumbnail: 'https://data.gameflare.com/games/11373/cje7pFPhVxZLhT-400-300.jpg',
    description: 'Your jump gets stronger every second — but so does the danger! Race through insane obstacle courses as your jumping power builds up in this wild Roblox-style obby.',
    rating: 4.6,
    plays: 5100000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Platformer', 'Arcade', '1 Player', 'Obby', 'Roblox', 'Skill', 'Fun'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '10m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'obby-but-youre-on-a-pogo',
    title: "Obby But You're on a Pogo",
    category: 'Platformer',
    url: "https://www.gameflare.com/embed/obby-but-you-re-on-a-pogo/",
    thumbnail: 'https://data.gameflare.com/games/10750/0i79ieTx6PgLbD-400-300.jpg',
    description: 'Complete the obstacle course... but you can only move by bouncing on a pogo stick! Master the chaotic physics, time your jumps and survive this hilariously challenging obby.',
    rating: 4.5,
    plays: 4200000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Platformer', 'Arcade', '1 Player', 'Obby', 'Roblox', 'Funny', 'Physics'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '10m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  // ── Casual / Sandbox / Brainrot (verified Gameflare embeds) ───────────
  {
    id: 'melon-sandbox',
    title: 'Melon Sandbox',
    category: 'Casual',
    url: 'https://www.gameflare.com/embed/melon-sandbox/',
    thumbnail: 'https://data.gameflare.com/games/10240/WbsP7C6K57nTrH-400-300.jpg',
    description: 'The wildly popular physics sandbox! Spawn ragdoll melons, set off explosions, drop objects and create total chaos. No rules, no objectives — just pure destructive sandbox fun.',
    rating: 4.7,
    plays: 11000000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: true,
    tags: ['Casual', 'Sandbox', '1 Player', 'Physics', 'Fun', 'Funny'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '15m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'sprunki',
    title: 'Sprunki',
    category: 'Casual',
    url: 'https://www.gameflare.com/embed/sprunki/',
    thumbnail: 'https://data.gameflare.com/games/10433/sekyTyR2FerKl7-400-300.jpg',
    description: 'The viral music creation game! Drag and drop quirky Sprunki characters onto the stage to layer beats, melodies and vocals into your own banger. A creative musical playground.',
    rating: 4.8,
    plays: 18000000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: true,
    tags: ['Casual', 'Music', 'Creative', '1 Player', 'Fun', 'Mobile'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'touch-friendly',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '15m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'sprunki-beat-attack',
    title: 'Sprunki Beat Attack',
    category: 'Casual',
    url: 'https://www.gameflare.com/embed/sprunki-beat-attack/',
    thumbnail: 'https://data.gameflare.com/games/11367/muS9wm8Xo0eU0x-400-300.jpg',
    description: 'Sprunki goes into battle mode! Combine the addictive music-mixing of Sprunki with rhythm-based combat. Drop beats, launch attacks and defeat enemies in time with your music.',
    rating: 4.6,
    plays: 6300000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Casual', 'Music', 'Action', 'Arcade', '1 Player', 'Rhythm'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'touch-friendly',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '10m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'tsunami-brainrots-online',
    title: 'Tsunami Brainrots Online',
    category: 'Action',
    url: 'https://www.gameflare.com/embed/tsunami-brainrots-online/',
    thumbnail: 'https://data.gameflare.com/games/11248/zNxhCHqYQ1LjEw-400-300.jpg',
    description: 'The wildest brainrot game online! Survive tsunami waves of chaos with your favourite meme characters in this totally unhinged multiplayer action game.',
    rating: 4.5,
    plays: 4800000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Action', 'Casual', 'Multiplayer', '1 Player', 'Funny', 'Meme'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '8m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
  {
    id: 'steal-brainrot-eggs',
    title: 'Steal Brainrot Eggs',
    category: 'Casual',
    url: 'https://www.gameflare.com/embed/steal-brainrot-eggs/',
    thumbnail: 'https://data.gameflare.com/games/11189/eiDU7IyaJkn1wg-400-300.jpg',
    description: 'Sneak in and steal the brainrot eggs before getting caught! A hilarious stealth casual game featuring your favourite meme characters and absurd brainrot humour.',
    rating: 4.4,
    plays: 3600000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: false,
    isTop: false,
    tags: ['Casual', 'Arcade', '1 Player', 'Funny', 'Meme', 'Stealth'],
    developer: 'Gameflare',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '8m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },

  {
    id: 'rivals-roblox',
    title: 'Rivals (Roblox)',
    category: 'Action',
    url: 'https://www.gameflare.com/embed/rivals-roblox/',
    thumbnail: 'https://data.gameflare.com/games/11236/oiRuQSeN3AQVEB-400-300.jpg',
    description: 'The hit Roblox shooter experience! Compete against rivals in fast-paced multiplayer combat, level up your character and dominate the leaderboard in this fan-favourite Roblox game.',
    rating: 4.6,
    plays: 6700000,
    authorUid: 'curated',
    createdAt: '2026-06-06T00:00:00.000Z',
    isHot: true,
    isTop: false,
    tags: ['Action', 'Shooting', 'Multiplayer', '1 Player', 'Roblox', 'Skill'],
    developer: 'Roblox',
    publisher: 'Gameflare',
    mobileOptimization: 'responsive',
    fullscreenSupport: true,
    orientation: 'landscape',
    embedCompatibility: 'full',
    validationState: 'Verified Working',
    lastVerified: '2026-06-06T00:00:00.000Z',
    sourceId: 'curated',
    avgPlayTime: '15m',
    contentRating: 'Everyone',
    adsInjected: false,
    popupRisk: false,
    redirectRisk: false,
  },
];
