import { Game } from './types';

export const CATEGORY_LIST = [
  "All",
  "Favorites",
  "Recommended",
  "History",
  "Trending",
  "Mods",
  "Action",
  "Adventure",
  "Arcade",
  "Card",
  "Casual",
  "Educational",
  "Multiplayer", 
  "2 Player", 
  "3 Player", 
  "4 Player",
  "Platformer",
  "Puzzle",
  "Racing",
  "Simulator",
  "Sports",
  "Strategy"
];

export const TAGS_LIST = [
  "Puzzle",
  "Logic",
  "Math",
  "Casual",
  "Strategy",
  "Arcade",
  "Action",
  "Match 3",
  "Tetris",
  "Shooter",
  "Retro",
  "Classic",
  "Skill",
  "Flappy Bird",
  "Maze",
  "Pac-Man",
  "Platformer",
  "Adventure",
  "Jump",
  "Racing",
  "Driving",
  "3D",
  "Flight",
  "PlayCanvas",
  "WebGL",
  "Sci-Fi",
  "Space",
  "js13k",
  "Twin-stick",
  "FPS",
  "Exploration",
  "Turn-based",
  "Fantasy",
  "Simulation",
  "RPG",
  "Endless",
  "Hacking",
  "Physics",
  "Arena",
  "Fast-paced",
  "Minimalist",
  "Snake",
  "Board Game",
  "2 Player",
  "Design",
  "Educational",
  "Typography",
  "Cellular Automata",
  "Sandbox",
  "Mashup",
  "Sudoku-like",
  "Archery",
  "Sports",
  "Soccer",
  "Football",
  "Grid",
  "Golf",
  "Horror",
  "Rhythm",
  "Music",
  "Survival",
  "Narrative",
  "Time-Loop",
  "Mining",
  "Timing",
  "Card",
  "Solitaire",
  "Board",
  "Tower Defense",
  "Magic",
  "Typing",
  "Management"
];

export const GAMES: Game[] = [
  {
    "id": "2048-original",
    "title": "2048",
    "category": "Puzzle",
    "url": "https://gabrielecirulli.github.io/2048/",
    "thumbnail": "/images/games/2048-original.svg",
    "description": "Join the numbers and get to the 2048 tile! The original addictive puzzle game by Gabriele Cirulli.",
    "rating": 4.8,
    "plays": 2500000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.664Z",
    "isHot": true,
    "isTop": true,
    "tags": [
      "Puzzle",
      "Logic",
      "Math",
      "Casual",
      "Strategy"
    ],
    "developer": "Gabriele Cirulli",
    "publisher": "Open Source",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "version": "1.0",
    "controls": "Swipe or use arrow keys, WASD to move tiles.",
    "tipsAndTricks": "Keep your highest value tile in one of the corners.",
    "whyYoullLikeIt": "Simple to learn but impossible to put down."
  },
  {
    "id": "hextris-io",
    "title": "Hextris",
    "category": "Puzzle",
    "url": "https://hextris.io/",
    "thumbnail": "/images/games/hextris-io.svg",
    "description": "An addictive puzzle game inspired by Tetris. Rotate the hexagon to catch the falling blocks and match colors.",
    "rating": 4.7,
    "plays": 1800000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "isHot": true,
    "isTop": true,
    "tags": [
      "Puzzle",
      "Arcade",
      "Action",
      "Match 3",
      "Tetris"
    ],
    "developer": "Logan Gabriel & Noah Moroze",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "version": "1.1",
    "controls": "Tap left/right sides or use left/right arrow keys to rotate.",
    "tipsAndTricks": "Focus on preventing stacks from breaching the outer boundary."
  },
  {
    "id": "duckhunt-js",
    "title": "Duck Hunt JS",
    "category": "Arcade",
    "url": "https://duckhunt.js.org/",
    "thumbnail": "/images/games/duckhunt-js.svg",
    "description": "A faithful HTML5 port of the classic NES game Duck Hunt. Aim, shoot, and see how far you can get!",
    "rating": 4.6,
    "plays": 1200000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "isHot": false,
    "tags": [
      "Arcade",
      "Shooter",
      "Retro",
      "Classic"
    ],
    "developer": "Matt Surabian",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Aim and tap/click to shoot."
  },
  {
    "id": "floppy-bird",
    "title": "Floppy Bird",
    "category": "Arcade",
    "url": "https://nebezb.com/floppybird/",
    "thumbnail": "/images/games/floppy-bird.svg",
    "description": "An open-source clone of the famously frustrating but addictive mobile game. Flap your way through the pipes!",
    "rating": 4.4,
    "plays": 3000000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "isHot": true,
    "tags": [
      "Arcade",
      "Skill",
      "Casual",
      "Retro",
      "Flappy Bird"
    ],
    "developer": "Nebez Briefkani",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Tap or click or press Spacebar to flap."
  },
  {
    "id": "pacman-js",
    "title": "Pac-Man JS",
    "category": "Arcade",
    "url": "https://pacman.platzh1rsch.ch/",
    "thumbnail": "/images/games/pacman-js.svg",
    "description": "A brilliant recreation of the original Pac-Man arcade game running fully in HTML5.",
    "rating": 4.9,
    "plays": 4000000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "isTop": true,
    "tags": [
      "Arcade",
      "Retro",
      "Classic",
      "Maze",
      "Pac-Man"
    ],
    "developer": "platzh1rsch",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrow keys to control Pac-Man."
  },
  {
    "id": "js-tiny-platformer",
    "title": "Tiny Platformer",
    "category": "Adventure",
    "url": "https://jakesgordon.github.io/javascript-tiny-platformer/",
    "thumbnail": "/images/games/js-tiny-platformer.svg",
    "description": "A very tiny 2D platformer engine written purely in JS by Jake Gordon.",
    "rating": 4.2,
    "plays": 800000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Platformer",
      "Adventure",
      "Retro",
      "Jump"
    ],
    "developer": "Jake Gordon",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrows to move, Space to jump."
  },
  {
    "id": "js-racer",
    "title": "JS Racer",
    "category": "Racing",
    "url": "https://jakesgordon.github.io/javascript-racer/v4.final.html",
    "thumbnail": "/images/games/js-racer.svg",
    "description": "Pseudo-3D racing game completely in HTML5/canvas inspired by Outrun.",
    "rating": 4.7,
    "plays": 1500000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Racing",
      "Driving",
      "Retro",
      "3D"
    ],
    "developer": "Jake Gordon",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrow keys to drive."
  },
  {
    "id": "swooop-playcanvas",
    "title": "Swooop",
    "category": "Action",
    "url": "https://playcanv.as/p/JtL2iqIH/",
    "thumbnail": "/images/games/swooop-playcanvas.svg",
    "description": "Fly a biplane and catch gems in this beautiful 3D WebGL game made with PlayCanvas.",
    "rating": 4.8,
    "plays": 950000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "isHot": true,
    "tags": [
      "3D",
      "Flight",
      "Action",
      "PlayCanvas",
      "WebGL"
    ],
    "developer": "PlayCanvas",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Hold space or screen to swoop up."
  },
  {
    "id": "astray-playkeepsafe",
    "title": "Astray",
    "category": "Puzzle",
    "url": "https://www.playkeepsafe.com/astray/",
    "thumbnail": "/images/games/astray-playkeepsafe.svg",
    "description": "A WebGL maze game built with Three.js. Roll a ball through a labyrinth.",
    "rating": 4.5,
    "plays": 870000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "3D",
      "Puzzle",
      "Maze",
      "WebGL"
    ],
    "developer": "Rik",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Use arrow keys to balance and navigate the maze."
  },
  {
    "id": "hexgl",
    "title": "HexGL",
    "category": "Racing",
    "url": "https://hexgl.bkcore.com/play/",
    "thumbnail": "/images/games/hexgl.svg",
    "description": "A futuristic fast-paced 3D racing game built using HTML5, JavaScript and WebGL.",
    "rating": 4.9,
    "plays": 5000000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "3D",
      "Racing",
      "Sci-Fi",
      "WebGL"
    ],
    "developer": "Thibaut Despoulain",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrow keys or A/D to steer."
  },
  {
    "id": "radius-raid",
    "title": "Radius Raid",
    "category": "Action",
    "url": "https://js13kgames.com/games/radius-raid/index.html",
    "thumbnail": "/images/games/radius-raid.svg",
    "description": "A space themed shoot 'em up where you must blast away unrelenting enemies before they destroy you.",
    "rating": 4.6,
    "plays": 450000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "isHot": true,
    "tags": [
      "Action",
      "Space",
      "Shooter",
      "js13k"
    ],
    "developer": "Jack Rugile",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "WASD/Arrows to move, Mouse to aim, Click to shoot.",
    "tipsAndTricks": "Collect dropping weapons and powerups to survive longer."
  },
  {
    "id": "space-huggers",
    "title": "Space Huggers",
    "category": "Action",
    "url": "https://js13kgames.com/games/space-huggers/index.html",
    "thumbnail": "/images/games/space-huggers.svg",
    "description": "Fast paced run and gun platformer with roguelike elements. Can you defeat the alien hive?",
    "rating": 4.8,
    "plays": 520000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "isTop": true,
    "tags": [
      "Platformer",
      "Action",
      "Shooter",
      "js13k"
    ],
    "developer": "Frank Force",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "WASD/Arrows to move. Z/C/Space to jump. X/V to shoot."
  },
  {
    "id": "underrun",
    "title": "Underrun",
    "category": "Action",
    "url": "https://js13kgames.com/games/underrun/index.html",
    "thumbnail": "/images/games/underrun.svg",
    "description": "A twin-stick shooter in WebGL. Dive into the dark facility, reboot the systems and survive.",
    "rating": 4.9,
    "plays": 600000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Twin-stick",
      "Shooter",
      "WebGL",
      "js13k"
    ],
    "developer": "Dominic Szablewski",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "WASD to move, Mouse to aim and shoot."
  },
  {
    "id": "q1k3",
    "title": "Q1K3",
    "category": "Action",
    "url": "https://js13kgames.com/games/q1k3/index.html",
    "thumbnail": "/images/games/q1k3.svg",
    "description": "A homage to Quake written in 13kb of JavaScript. Fast 3D retro action.",
    "rating": 4.9,
    "plays": 780000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "isHot": true,
    "tags": [
      "FPS",
      "Retro",
      "3D",
      "Action",
      "js13k"
    ],
    "developer": "PhobosLab",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "WASD to move, Mouse to aim and shoot. Space to jump."
  },
  {
    "id": "evil-glitch",
    "title": "Evil Glitch",
    "category": "Action",
    "url": "https://js13kgames.com/games/evil-glitch/index.html",
    "thumbnail": "/images/games/evil-glitch.svg",
    "description": "Survive in a glitching dimension. A frantic twin-stick shooter with beautiful effects.",
    "rating": 4.7,
    "plays": 320000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Arcade",
      "Shooter",
      "js13k"
    ],
    "developer": "Utopian Games",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrows for movement, Mouse for aiming/shooting."
  },
  {
    "id": "offline",
    "title": "Offline",
    "category": "Adventure",
    "url": "https://js13kgames.com/games/offline/index.html",
    "thumbnail": "/images/games/offline.svg",
    "description": "You are a little robot exploring a vast underground world to find the internet connection.",
    "rating": 4.5,
    "plays": 150000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Adventure",
      "Platformer",
      "Exploration",
      "js13k"
    ],
    "developer": "Tomek Sułkowski",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrow keys to move, Z to jump."
  },
  {
    "id": "the-wizards-turn",
    "title": "The Wizard's Turn",
    "category": "Strategy",
    "url": "https://js13kgames.com/games/the-wizards-turn/index.html",
    "thumbnail": "/images/games/the-wizards-turn.svg",
    "description": "Turn-based tactical combat where you must defend the kingdom using powerful spells.",
    "rating": 4.4,
    "plays": 90000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Strategy",
      "Turn-based",
      "Fantasy",
      "js13k"
    ],
    "developer": "Zat",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Mouse to select and cast spells."
  },
  {
    "id": "re-wire",
    "title": "Re-wire",
    "category": "Puzzle",
    "url": "https://js13kgames.com/games/re-wire/index.html",
    "thumbnail": "/images/games/re-wire.svg",
    "description": "Connect all the colored nodes without crossing paths. A challenging brain teaser.",
    "rating": 4.6,
    "plays": 210000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Puzzle",
      "Logic",
      "Casual",
      "js13k"
    ],
    "developer": "Kee-Yip Chan",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Drag with mouse or touch from one node to its matching color."
  },
  {
    "id": "13",
    "title": "13",
    "category": "Puzzle",
    "url": "https://js13kgames.com/games/13/index.html",
    "thumbnail": "/images/games/13.svg",
    "description": "A clever logic puzzle. Can you reach the number 13?",
    "rating": 4.3,
    "plays": 110000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Puzzle",
      "Math",
      "js13k"
    ],
    "developer": "Tomek Sułkowski",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Click to select, click another to merge."
  },
  {
    "id": "everyone-s-sky",
    "title": "Everyone's Sky",
    "category": "Adventure",
    "url": "https://js13kgames.com/games/everyones-sky/index.html",
    "thumbnail": "/images/games/everyone-s-sky.svg",
    "description": "Explore the galaxy, trade goods, fight pirates, and discover new planets in this miniature space sim.",
    "rating": 4.8,
    "plays": 400000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Space",
      "Simulation",
      "RPG",
      "Adventure",
      "js13k"
    ],
    "developer": "B.A.B.",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "WASD to accelerate/steer. Space to interact."
  },
  {
    "id": "lost-in-cyberspace",
    "title": "Lost in Cyberspace",
    "category": "Action",
    "url": "https://js13kgames.com/games/lost-in-cyberspace/index.html",
    "thumbnail": "/images/games/lost-in-cyberspace.svg",
    "description": "Navigate a geometric cyberspatial realm and dodge incoming obstacles at high speed.",
    "rating": 4.2,
    "plays": 75000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Action",
      "Arcade",
      "Endless",
      "js13k"
    ],
    "developer": "S.F.",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrow keys to move."
  },
  {
    "id": "dante",
    "title": "Dante",
    "category": "Platformer",
    "url": "https://js13kgames.com/games/dante/index.html",
    "thumbnail": "/images/games/dante.svg",
    "description": "A beautiful pixel art puzzle platformer where you control two characters simultaneously.",
    "rating": 4.7,
    "plays": 180000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Puzzle",
      "Platformer",
      "js13k"
    ],
    "developer": "Tomek Sułkowski",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrow keys to move and jump."
  },
  {
    "id": "super-chronoman",
    "title": "Super Chronoman",
    "category": "Platformer",
    "url": "https://js13kgames.com/games/super-chronoman/index.html",
    "thumbnail": "/images/games/super-chronoman.svg",
    "description": "Run, jump, and control time in this challenging 2D platformer.",
    "rating": 4.4,
    "plays": 105000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Platformer",
      "Action",
      "js13k"
    ],
    "developer": "H.B.",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "WASD to move, Space to Shift Time."
  },
  {
    "id": "glitch-buster",
    "title": "Glitch Buster",
    "category": "Action",
    "url": "https://js13kgames.com/games/glitch-buster/index.html",
    "thumbnail": "/images/games/glitch-buster.svg",
    "description": "A fast-paced arcade shooter. Clear the glitches before the system crashes.",
    "rating": 4.1,
    "plays": 60000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Action",
      "Retro",
      "js13k"
    ],
    "developer": "C.R.",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Mouse to aim and shoot."
  },
  {
    "id": "xx142-b2-exe",
    "title": "XX142-B2.EXE",
    "category": "Puzzle",
    "url": "https://js13kgames.com/games/xx142-b2.exe/index.html",
    "thumbnail": "/images/games/xx142-b2-exe.svg",
    "description": "A hacking logic puzzle game. Bypass security nodes and execute the payload.",
    "rating": 4.8,
    "plays": 240000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Puzzle",
      "Logic",
      "Hacking",
      "js13k"
    ],
    "developer": "Oleg",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Mouse to interact with nodes."
  },
  {
    "id": "geoslam",
    "title": "GeoSlam",
    "category": "Action",
    "url": "https://js13kgames.com/games/geoslam/index.html",
    "thumbnail": "/images/games/geoslam.svg",
    "description": "Slam into geometry! Fast paced physics arena combat.",
    "rating": 4.3,
    "plays": 90000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Action",
      "Physics",
      "Arena",
      "js13k"
    ],
    "developer": "M.K.",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Mouse to aim and propel yourself."
  },
  {
    "id": "taxi-drift",
    "title": "Taxi Drift",
    "category": "Racing",
    "url": "https://js13kgames.com/games/taxi-drift/index.html",
    "thumbnail": "/images/games/taxi-drift.svg",
    "description": "Drift your taxi through busy city streets and pick up passengers.",
    "rating": 4.5,
    "plays": 130000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Racing",
      "Driving",
      "js13k"
    ],
    "developer": "A.S.",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrow keys to drive and drift."
  },
  {
    "id": "highway-404",
    "title": "Highway 404",
    "category": "Racing",
    "url": "https://js13kgames.com/games/highway-404/index.html",
    "thumbnail": "/images/games/highway-404.svg",
    "description": "Retro infinite racing on a procedurally generated highway.",
    "rating": 4.4,
    "plays": 150000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Racing",
      "Retro",
      "js13k"
    ],
    "developer": "N.D.",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Left/Right arrows to steer."
  },
  {
    "id": "packet-shuffle",
    "title": "Packet Shuffle",
    "category": "Puzzle",
    "url": "https://js13kgames.com/games/packet-shuffle/index.html",
    "thumbnail": "/images/games/packet-shuffle.svg",
    "description": "Sort incoming data packets to the correct output streams before overflowing.",
    "rating": 4.2,
    "plays": 50000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Puzzle",
      "Fast-paced",
      "js13k"
    ],
    "developer": "J.M.",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Click/Tap to rotate junctions."
  },
  {
    "id": "on-off",
    "title": "On/Off",
    "category": "Puzzle",
    "url": "https://js13kgames.com/games/on-off/index.html",
    "thumbnail": "/images/games/on-off.svg",
    "description": "A minimalist puzzle game where you toggle states to clear levels.",
    "rating": 4.1,
    "plays": 40000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Puzzle",
      "Minimalist",
      "js13k"
    ],
    "developer": "T.L.",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Click/Tap to toggle tiles."
  },
  {
    "id": "js-tetris",
    "title": "JavaScript Tetris",
    "category": "Arcade",
    "url": "https://jakesgordon.github.io/javascript-tetris/",
    "thumbnail": "/images/games/js-tetris.svg",
    "description": "Classic Tetris implemented in pure JavaScript and Canvas. A timeless favorite.",
    "rating": 4.9,
    "plays": 800000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "isTop": true,
    "tags": [
      "Puzzle",
      "Arcade",
      "Retro",
      "Classic",
      "Tetris"
    ],
    "developer": "Jake Gordon",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrow keys to move/rotate, Space to drop."
  },
  {
    "id": "js-snake",
    "title": "JavaScript Snake",
    "category": "Arcade",
    "url": "https://jakesgordon.github.io/javascript-snakes/",
    "thumbnail": "/images/games/js-snake.svg",
    "description": "Eat the apples, grow the snake, don't bite yourself. Simple and fun.",
    "rating": 4.7,
    "plays": 650000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Arcade",
      "Snake",
      "Retro",
      "Classic"
    ],
    "developer": "Jake Gordon",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrow keys to steer."
  },
  {
    "id": "clumsy-bird",
    "title": "Clumsy Bird",
    "category": "Arcade",
    "url": "https://ellisonleao.github.io/clumsy-bird/",
    "thumbnail": "/images/games/clumsy-bird.svg",
    "description": "An open source MelonJS clone of the famous game featuring a clumsy bird.",
    "rating": 4.3,
    "plays": 2200000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Arcade",
      "Casual",
      "Skill"
    ],
    "developer": "Ellison Leão",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Click or tap to fly."
  },
  {
    "id": "tic-tac-toe",
    "title": "Tic Tac Toe",
    "category": "Puzzle",
    "url": "https://mkismurphy.github.io/TicTacToe/",
    "thumbnail": "/images/games/tic-tac-toe.svg",
    "description": "Classic Tic Tac Toe game to play against the computer or a friend on the same screen.",
    "rating": 4,
    "plays": 100000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Puzzle",
      "Board Game",
      "2 Player",
      "Casual"
    ],
    "developer": "Murphy",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Tap or click on a square to place your mark."
  },
  {
    "id": "color-method",
    "title": "Color Match",
    "category": "Educational",
    "url": "https://color.method.ac/",
    "thumbnail": "/images/games/color-method.svg",
    "description": "A color matching game. Test how well you can distinguish hue, saturation, and complimentary colors.",
    "rating": 4.9,
    "plays": 1200000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Design",
      "Educational",
      "Puzzle"
    ],
    "developer": "Method of Action",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Mouse to adjust the color wheel."
  },
  {
    "id": "shape-type",
    "title": "Shape Type",
    "category": "Educational",
    "url": "https://shape.method.ac/",
    "thumbnail": "/images/games/shape-type.svg",
    "description": "A letter shaping game. Test your typographic skills by adjusting vector points.",
    "rating": 4.8,
    "plays": 900000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Design",
      "Educational",
      "Puzzle",
      "Typography"
    ],
    "developer": "Method of Action",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Drag bezier curve handles to shape letters."
  },
  {
    "id": "kern-type",
    "title": "Kern Type",
    "category": "Educational",
    "url": "https://type.method.ac/",
    "thumbnail": "/images/games/kern-type.svg",
    "description": "A kerning game. Distribute the space between a sequence of letters perfectly.",
    "rating": 4.9,
    "plays": 1500000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Design",
      "Educational",
      "Puzzle",
      "Typography"
    ],
    "developer": "Method of Action",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Drag letters left or right."
  },
  {
    "id": "game-of-life",
    "title": "Conway's Game of Life",
    "category": "Simulator",
    "url": "https://playgameoflife.com/",
    "thumbnail": "/images/games/game-of-life.svg",
    "description": "The classic cellular automaton created by mathematician John Horton Conway.",
    "rating": 4.5,
    "plays": 300000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Simulation",
      "Cellular Automata",
      "Math",
      "Sandbox"
    ],
    "developer": "playgameoflife",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Click to toggle cells, use controls to start simulation."
  },
  {
    "id": "2048-tetris",
    "title": "2048 Tetris",
    "category": "Puzzle",
    "url": "https://prat0318.github.io/2048-tetris/",
    "thumbnail": "/images/games/2048-tetris.svg",
    "description": "A fantastic blend of 2048 and Tetris mechanics. Drop blocks with numbers to merge them.",
    "rating": 4.6,
    "plays": 450000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Puzzle",
      "Math",
      "Tetris",
      "Mashup"
    ],
    "developer": "Prateek Agarwal",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrow keys to move, Up to rotate, Down to drop."
  },
  {
    "id": "oh-hi",
    "title": "0h h1",
    "category": "Puzzle",
    "url": "https://0hh1.com/",
    "thumbnail": "/images/games/oh-hi.svg",
    "description": "A little logic game by Q42. No three red or blue tiles next to each other. A full row or column must have as many red chips as blue.",
    "rating": 4.9,
    "plays": 2000000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "isTop": true,
    "tags": [
      "Puzzle",
      "Logic",
      "Sudoku-like",
      "Casual"
    ],
    "developer": "Q42",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Tap/Click spots to toggle red, blue, or blank."
  },
  {
    "id": "oh-no",
    "title": "0h n0",
    "category": "Puzzle",
    "url": "https://0hn0.com/",
    "thumbnail": "/images/games/oh-no.svg",
    "description": "A lovely companion to 0h h1. Blue dots can see others in their row/col, red block the view.",
    "rating": 4.9,
    "plays": 1800000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Puzzle",
      "Logic",
      "Casual"
    ],
    "developer": "Q42",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Tap/Click to place blue or red dots based on the clues."
  },
  {
    "id": "master-archer",
    "title": "Master Archer",
    "category": "Sports",
    "url": "https://playcanv.as/p/2OlkUaxF/",
    "thumbnail": "/images/games/master-archer.svg",
    "description": "Aim carefully and shoot the apple off the man's head! A classic archery skill game.",
    "rating": 4.6,
    "plays": 1100000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Archery",
      "Sports",
      "Skill",
      "Casual",
      "PlayCanvas"
    ],
    "developer": "PlayCanvas",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Tap and hold to aim, release to shoot."
  },
  {
    "id": "keepy-up",
    "title": "Keepy Up",
    "category": "Sports",
    "url": "https://playcanv.as/p/6d3E3fJj/",
    "thumbnail": "/images/games/keepy-up.svg",
    "description": "Keep the soccer ball in the air as long as possible. Test your reflexes in this 3D WebGL game.",
    "rating": 4.2,
    "plays": 800000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Sports",
      "Soccer",
      "Football",
      "Skill",
      "PlayCanvas",
      "WebGL"
    ],
    "developer": "PlayCanvas",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Click or tap underneath the ball to keep it bouncing up."
  },
  {
    "id": "accelerally",
    "title": "Accelerally",
    "category": "Racing",
    "url": "https://playcanv.as/p/X5b7S1F7/",
    "thumbnail": "/images/games/accelerally.svg",
    "description": "Race through a neon landscape, avoid obstacles and go as fast as you can.",
    "rating": 4.4,
    "plays": 450000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Racing",
      "Endless",
      "3D",
      "PlayCanvas"
    ],
    "developer": "PlayCanvas",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrow keys or A/D to steer laterally."
  },
  {
    "id": "samurai-sokoban",
    "title": "Samurai Sokoban",
    "category": "Puzzle",
    "url": "https://js13kgames.com/games/samurai-sokoban/index.html",
    "thumbnail": "/images/games/samurai-sokoban.svg",
    "description": "A fresh take on the classic Sokoban box-pushing puzzle but with samurai theme. Very polished.",
    "rating": 4.7,
    "plays": 120000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Puzzle",
      "Logic",
      "Grid",
      "js13k"
    ],
    "developer": "Samurai Devs",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrow keys to move, push blocks."
  },
  {
    "id": "mini-golf-13k",
    "title": "Mini Golf",
    "category": "Sports",
    "url": "https://js13kgames.com/games/mini-golf/index.html",
    "thumbnail": "/images/games/mini-golf-13k.svg",
    "description": "A fun and challenging 2D mini-golf game built for the js13k competition.",
    "rating": 4.5,
    "plays": 250000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Golf",
      "Sports",
      "Physics",
      "js13k"
    ],
    "developer": "Unknown",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Drag mouse or touch to aim and set power, release to putt."
  },
  {
    "id": "dead-space-13",
    "title": "Dead Space",
    "category": "Action",
    "url": "https://js13kgames.com/games/dead-space/index.html",
    "thumbnail": "/images/games/dead-space-13.svg",
    "description": "A tense, top-down space survival horror shooter. Conserve your ammo and watch for movement.",
    "rating": 4.8,
    "plays": 300000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Action",
      "Horror",
      "Shooter",
      "js13k"
    ],
    "developer": "Indie Devs",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "WASD to move, Mouse to aim and shoot."
  },
  {
    "id": "shifting-shadows",
    "title": "Shifting Shadows",
    "category": "Puzzle",
    "url": "https://js13kgames.com/games/shifting-shadows/index.html",
    "thumbnail": "/images/games/shifting-shadows.svg",
    "description": "A puzzle game about matching light and shadow patterns. Relaxing and engaging.",
    "rating": 4.6,
    "plays": 80000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Puzzle",
      "Logic",
      "js13k"
    ],
    "developer": "Shadow Devs",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Click or tap to rotate blocks."
  },
  {
    "id": "beat-subway",
    "title": "Beat Subway",
    "category": "Arcade",
    "url": "https://js13kgames.com/games/beat-subway/index.html",
    "thumbnail": "/images/games/beat-subway.svg",
    "description": "A rhythmic reaction game where you must dodge incoming trains to the beat.",
    "rating": 4.3,
    "plays": 150000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Rhythm",
      "Music",
      "Arcade",
      "js13k"
    ],
    "developer": "BeatMaker",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Left/Right/Up/Down arrows on the beat."
  },
  {
    "id": "knight-game",
    "title": "Knight Game",
    "category": "Adventure",
    "url": "https://js13kgames.com/games/knight-game/index.html",
    "thumbnail": "/images/games/knight-game.svg",
    "description": "A small RPG adventure fighting through dungeons, collecting weapons, and slaying the dragon.",
    "rating": 4.7,
    "plays": 220000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "RPG",
      "Adventure",
      "Fantasy",
      "js13k"
    ],
    "developer": "Sword Dev",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrow keys to move, Z to attack, X to interact."
  },
  {
    "id": "maze-of-death",
    "title": "Maze of Death",
    "category": "Action",
    "url": "https://js13kgames.com/games/maze-of-death/index.html",
    "thumbnail": "/images/games/maze-of-death.svg",
    "description": "Run from incoming danger while solving labyrinth puzzles on the fly.",
    "rating": 4.2,
    "plays": 95000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Action",
      "Puzzle",
      "Survival",
      "js13k"
    ],
    "developer": "Maze Runners",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "WASD to move quickly."
  },
  {
    "id": "a-thirteenth-chance",
    "title": "Thirteenth Chance",
    "category": "Strategy",
    "url": "https://js13kgames.com/games/a-thirteenth-chance/index.html",
    "thumbnail": "/images/games/a-thirteenth-chance.svg",
    "description": "A time-loop game where you only have 13 attempts to prevent a historical disaster from occurring.",
    "rating": 4.8,
    "plays": 175000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Strategy",
      "Narrative",
      "Time-Loop",
      "js13k"
    ],
    "developer": "Time Weaver",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Mouse to select timeline branches."
  },
  {
    "id": "subterrene",
    "title": "Subterrene",
    "category": "Adventure",
    "url": "https://js13kgames.com/games/subterrene/index.html",
    "thumbnail": "/images/games/subterrene.svg",
    "description": "Dig your way into an ancient, underground cavern system to retrieve lost relics.",
    "rating": 4.6,
    "plays": 135000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Adventure",
      "Mining",
      "Exploration",
      "js13k"
    ],
    "developer": "Cave Digger",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrow keys to move, Dig automatically."
  },
  {
    "id": "little-alchemy-clone",
    "title": "Elements",
    "category": "Puzzle",
    "url": "https://krunel.github.io/Elements-Game/",
    "thumbnail": "/images/games/little-alchemy-clone.svg",
    "description": "Combine basic elements to discover hundreds of new ones. A simple alchemy game clone.",
    "rating": 4.5,
    "plays": 500000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Puzzle",
      "Sandbox",
      "Logic"
    ],
    "developer": "Krunel",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Drag and drop elements onto the board or onto each other to combine."
  },
  {
    "id": "core-ball-clone",
    "title": "Core Ball",
    "category": "Arcade",
    "url": "https://core-ball.github.io/",
    "thumbnail": "/images/games/core-ball-clone.svg",
    "description": "Attach small balls to the core without hitting existing ones. Incredibly difficult timing game.",
    "rating": 4.9,
    "plays": 4000000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "isTop": true,
    "tags": [
      "Arcade",
      "Timing",
      "Skill",
      "Casual"
    ],
    "developer": "Unknown",
    "mobileOptimization": "touch-friendly",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Tap or click the screen to launch a pin."
  },
  {
    "id": "spider-solitaire",
    "title": "Spider Solitaire",
    "category": "Card",
    "url": "https://mrdoob.com/projects/cards/",
    "thumbnail": "/images/games/spider-solitaire.svg",
    "description": "A classic, elegant rendering of Spider Solitaire by the creator of Three.js.",
    "rating": 4.4,
    "plays": 800000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Card",
      "Solitaire",
      "Casual",
      "Board"
    ],
    "developer": "Mr. Doob",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Click and drag to move cards."
  },
  {
    "id": "defender-13k",
    "title": "Defender",
    "category": "Strategy",
    "url": "https://js13kgames.com/games/defender/index.html",
    "thumbnail": "/images/games/defender-13k.svg",
    "description": "A minimalist tower defense game where you protect the core from incoming enemy waves.",
    "rating": 4.6,
    "plays": 150000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Strategy",
      "Tower Defense",
      "js13k"
    ],
    "developer": "TD Devs",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Click to build and upgrade towers."
  },
  {
    "id": "super-13-knight",
    "title": "13 Knight",
    "category": "Action",
    "url": "https://js13kgames.com/games/super-13-knight/index.html",
    "thumbnail": "/images/games/super-13-knight.svg",
    "description": "Side-scrolling platformer action. Collect coins, defeat slimes and rescue the princess.",
    "rating": 4.3,
    "plays": 130000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Action",
      "Platformer",
      "Magic",
      "js13k"
    ],
    "developer": "Retro Studio",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Arrows to move, Space to Jump, X to attack."
  },
  {
    "id": "z-typer",
    "title": "Z-Typer",
    "category": "Educational",
    "url": "https://js13kgames.com/games/z-typer/index.html",
    "thumbnail": "/images/games/z-typer.svg",
    "description": "A fast paced typing game where words attack you like spaceships. Type to destroy.",
    "rating": 4.8,
    "plays": 340000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Educational",
      "Typing",
      "Action",
      "Shooter",
      "js13k"
    ],
    "developer": "Tomek Sułkowski",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Type the letters appearing on enemy ships on your keyboard."
  },
  {
    "id": "spaceport-manager",
    "title": "Spaceport Manager",
    "category": "Strategy",
    "url": "https://js13kgames.com/games/spaceport/index.html",
    "thumbnail": "/images/games/spaceport-manager.svg",
    "description": "Manage traffic, resource fuel and coordinate spaceship docks in this micro-management game.",
    "rating": 4.4,
    "plays": 85000,
    "authorUid": "system",
    "createdAt": "2026-05-30T13:32:49.665Z",
    "tags": [
      "Strategy",
      "Management",
      "Simulation",
      "Space",
      "js13k"
    ],
    "developer": "SimHQ",
    "mobileOptimization": "desktop-only",
    "fullscreenSupport": true,
    "embedCompatibility": "full",
    "validationState": "Verified Working",
    "lastVerified": "2026-05-30T13:32:49.665Z",
    "controls": "Mouse to manage UI and direct traffic."
  }
];
